#!/bin/bash
# Test normal encrypted communication

echo "=================================="
echo "Test 1: Normal Communication"
echo "=================================="
echo ""
echo "This test demonstrates:"
echo "  - Certificate exchange and validation"
echo "  - User authentication"
echo "  - DH key exchange"
echo "  - Encrypted messaging"
echo "  - Non-repudiation (transcripts & receipts)"
echo ""
echo "Instructions:"
echo "  1. Wireshark should be capturing on 'lo' interface"
echo "  2. Filter: tcp.port == 5555"
echo "  3. Start server in Terminal 1"
echo "  4. Start client in Terminal 2"
echo "  5. Register/login and exchange messages"
echo "  6. Type 'exit' to end session"
echo "  7. Verify transcripts are created"
echo ""
read -p "Press Enter to continue..."
